var BeneSpeak={wordHighlightClass:"ttsWordHL",sentenceHighlightClass:"ttsSentHL",BOUNDARY_CHARS:/[\.,](?=\s|$)|[\!\?\s\"\;\u201c\u201d\u2013\u2014]/g,SENTENCE_TERMINATORS:/[\.\?\!]/,WORD_SEPARATORS:/[\s",;\u201c\u201d\u2013\u2014]/,CONDITIONAL_SEPARATORS:/'\u2018\u2019/,IGNORE_ELEMENTS:/beelinespan/,SpeechData:function(){this.document=null;this.utterance="";this.words=[];this.sentences=[];this._highlightedSentence=this._highlightedWord=-1;this._sipStart=null;this._sipOffset=-1;this._wipStart=null;
this._wordRects=[];this._sentenceRects=[];this.yOffset=this.xOffset=0},Fragment:function(a,c){this.range=a;this.offset=c;this.text=this.range.toString()},Position:function(a,c){this.node=a;this.offset=c},generateSpeechData:function(a){r=new BeneSpeak.SpeechData;BeneSpeak._tokenize(a,r);return r},_tokenize:function(a,c){if(c.document==null)c.document=a.ownerDocument;switch(a.nodeType){case Node.ELEMENT_NODE:for(var b=a.childNodes,d=0;d<b.length;d++)this._tokenize(b[d],c);BeneSpeak._processElementBoundary(c,
a);break;case Node.TEXT_NODE:b=a.textContent;if(c._wipStart==null&&(d=/\S/.exec(b),d!=null))c._wipStart=new BeneSpeak.Position(a,d.index);if(c._wipStart!=null)for(d=this.BOUNDARY_CHARS.exec(b);d!=null;){if(c._sipStart==null)c._sipStart=c._wipStart.copy(),c._sipOffset=c.utterance.length;BeneSpeak._processWordBoundary(c,a,d);this.SENTENCE_TERMINATORS.test(d[0])==!0&&(c.utterance+=" ",BeneSpeak._processSentenceBoundary(c,a,d));d=this.BOUNDARY_CHARS.exec(b)}}return c},speak:function(a,c){var b=this.generateSpeechData(a);
chrome.tts.speak(b.utterance,{rate:1.25,onEvent:function(a){b.handleTtsEvent(a,c)}})},stop:function(){chrome.tts.stop()},_isBlockElement:function(a){a=window.getComputedStyle(a);return a.display.indexOf("inline")==-1&&a.display.indexOf("ruby")==-1},_processWordBoundary:function(a,c,b){var d=a.document.createRange();d.setStart(a._wipStart.node,a._wipStart.offset);d.setEnd(c,b.index);d=new BeneSpeak.Fragment(d,a.utterance.length);d.text.length>0&&a.words.push(d);a.utterance+=d.text;a.utterance+=b[0];
a._wipStart=b.index+1<c.textContent.length?new BeneSpeak.Position(c,b.index+1):null},_processSentenceBoundary:function(a,c,b){var d=a.document.createRange();d.setStart(a._sipStart.node,a._sipStart.offset);d.setEnd(c,b.index+1);for(c=0;c<a.words.length;c++)if(b=a.words[c].range.startOffset,b.startContainer==a._sipStart.node&&b.startOffset==a._sipStart.offset)break;d=new BeneSpeak.Fragment(d,a._sipOffset);d.text.length>0&&a.sentences.push(d);a._sipStart=null;a._sipOffset=0},_processElementBoundary:function(a,
c){var b=this.IGNORE_ELEMENTS.test(c.nodeName);if(a._wipStart!=null&&!b){var d=a.document.createRange();d.setStart(a._wipStart.node,a._wipStart.offset);d.setEndAfter(c);d=new BeneSpeak.Fragment(d,a.utterance.length);d.text.length>0&&a.words.push(d);a.utterance+=d.text;a._wipStart=null}if(a._sipStart!=null&&this._isBlockElement(c))d=a.document.createRange(),d.setStart(a._sipStart.node,a._sipStart.offset),d.setEndAfter(c),d=new BeneSpeak.Fragment(d,a._sipOffset),d.text.length>0&&a.sentences.push(d),
a._sipStart=null,a._sipOffset=0;b||(a.utterance+="\n")},_elementStartAnnouncement:function(a,c){var b=c.tagName.toLowerCase();b=="table"?a.utterance+="\nBegin table. ":b=="tr"?a.utterance+="\nBegin table row. ":b=="td"?a.utterance+="\nTable cell. ":b=="ol"?a.utterance+="\nBegin ordered list. ":b=="ul"?a.utterance+="\nBegin list. ":b=="li"&&(a.utterance+="\nList item. ")},_elementEndAnnouncement:function(a,c){var b=c.tagName.toLowerCase();b=="table"?a.utterance+="\nEnd table. ":b=="tr"?a.utterance+=
"\nEnd table row. ":b=="ol"?a.utterance+="\nEnd ordered list. ":b=="ul"&&(a.utterance+="\nEnd list. ")}};BeneSpeak.SpeechData.prototype.clearWordHighlight=function(){for(;this._wordRects.length>0;)this.document.body.removeChild(this._wordRects.pop());this._highlightedWord=-1};BeneSpeak.SpeechData.prototype.clearSentenceHighlight=function(){for(;this._sentenceRects.length>0;)this.document.body.removeChild(this._sentenceRects.pop());this._highlightedSentence=-1};
BeneSpeak.SpeechData.prototype.handleTtsEvent=function(a,c){if(a.type=="word"){var b=this.wordAt(a.charIndex);b>=0&&this.highlightWord(b);b=this.sentenceAt(a.charIndex);b>=0&&this.highlightSentence(b)}else if(a.type=="interrupted"||a.type=="end")this.clearWordHighlight(),this.clearSentenceHighlight(),c!=null&&c()};
BeneSpeak.SpeechData.prototype.highlightWord=function(a){if(this._highlightedWord!=a){this.clearWordHighlight();this._highlightedWord=a;for(var a=this.words[a].range.getClientRects(),c=0;c<a.length;c++){var b=this.document.createElement("div");this.document.body.appendChild(b);b.className=BeneSpeak.wordHighlightClass;b.style.position="absolute";b.style.top=a[c].top+window.scrollY+this.yOffset+"px";b.style.left=a[c].left+window.scrollX+this.xOffset+"px";b.style.width=a[c].width+"px";b.style.height=
a[c].height+"px";this._wordRects.push(b)}}};
BeneSpeak.SpeechData.prototype.highlightSentence=function(a){if(this._highlightedSentence!=a){this.clearSentenceHighlight();this._highlightedSentence=a;for(var a=this.sentences[a].range.getClientRects(),c=0;c<a.length;c++){var b=this.document.createElement("div");this.document.body.appendChild(b);b.className=BeneSpeak.sentenceHighlightClass;b.style.position="absolute";b.style.top=a[c].top+window.scrollY+this.yOffset+"px";b.style.left=a[c].left+window.scrollX+this.xOffset+"px";b.style.width=a[c].width+
"px";b.style.height=a[c].height+"px";this._sentenceRects.push(b)}}};BeneSpeak.SpeechData.prototype._getOffset=function(a){return a.slice(-2)=="px"?0-parseInt(a.substring(0,a.length-2)):0};BeneSpeak.SpeechData.prototype.wordAt=function(a,c){for(var b=c?0:this._highlightedWord==-1?0:this._highlightedWord;b<this.words.length;b++){if(a<this.words[b].offset)return b-1;if(this.words[b].includes(a))return b}return-1};
BeneSpeak.SpeechData.prototype.sentenceAt=function(a,c){for(var b=c?0:this._highlightedSentence==-1?0:this._highlightedSentence;b<this.sentences.length;b++)if(a<this.sentences[b].offset)return b-1;else if(this.sentences[b].includes(a))return b;return-1};BeneSpeak.Fragment.prototype.includes=function(a){return a>=this.offset&&a<this.offset+this.text.length};BeneSpeak.Position.prototype.copy=function(){return new BeneSpeak.Position(this.node,this.offset)};
