window.BookshareUtils={environment:"LIVE",ie9Flag:null,POSITION_TRACKING_EXCLUSIONS:["html","section","div"],AWS_URL_PATTERN:/https\:\/\/(?:(qa|staging)\-){0,1}bookshare\-reader\.s3\.amazonaws\.com\/(?:\w+\/)?viewer\.html\?book=(\d*)/,isIOS:function(){if(this.iosFlag==null)this.iosFlag=["iPhone","iPad","iPod"].indexOf(navigator.platform)>-1;return this.iosFlag},isAndroidOrWindowsPhone:function(){return/android/i.test(navigator.userAgent||navigator.vendor||window.opera)},isChromeOS:function(){return navigator.appVersion.indexOf("CrOS")!=
-1},isFirefox:function(){return typeof InstallTrigger!=="undefined"},isIE:function(){return!!document.documentMode},isEdge:function(){return!this.isIE()&&!!window.StyleMedia},hasSpeechAPI:function(){return(window.speechSynthesis&&window.speechSynthesis.getVoices&&window.SpeechSynthesisUtterance)!=void 0&&!this.isIOS()},offerChromeExtension:function(){return window.chrome&&!this.hasSpeechAPI()&&!window.chrome.extension&&navigator.userAgent.indexOf("Android")==-1&&BookshareUtils.environment=="LIVE"&&
navigator.userAgent.search(/silk/i)==-1},flatten:function(a){return this.environment=="DEV"?a.substr(a.lastIndexOf("/")):a},makeSyncFunction:function(a,b,d){return function(e,c,f){c=a(c);if(!c)throw"Cannot sync the model without a valid sync URL.";switch(e){case "read":e={url:c,dataType:b,xhrFields:{withCredentials:!0},crossDomain:!0,success:function(a){f.success(a)},error:function(a){f.error(a)}};if(d)e.dataType="jsonp "+b,e.xhrFields=null;$.ajax(e);break;case "create":throw"Not yet implemented";
case "update":throw"Not yet implemented";case "delete":throw"Not yet implemented";}return null}},resolveUrl:function(a){var b;b=a.substring(0,3)=="../"?a.substring(3):a;b=BookshareUtils.flatten(b);a=window._epub.packageDocument.get("manifest").find(function(a){return(new URI(a.get("href"))).path.indexOf(b)>-1});return a==null?null:a.get("href")},setEnvironment:function(a){BookshareUtils.http="https://";var b=/\/(\w+)\/viewer.html/.exec(location.pathname);BookshareUtils.domain=(b?b[1]:"bookshare")+
".org";if(/\bdev\b/.test(location.hostname))BookshareUtils.environment="DEV",BookshareUtils.http="http://";else if(a=window.chrome&&window.chrome.extension?/chrome\-extension\:\/\/\w*?\/views\/viewer\.html\?book=\d*?(?:&env=(\w*))/.exec(a):BookshareUtils.AWS_URL_PATTERN.exec(a),a!=null)if(a[1]=="qa")BookshareUtils.environment="QA";else if(a[1]=="staging")BookshareUtils.environment="STAGING"},resolveEnvironment:function(a){a=new URI(a);if(a.authority=="www.bookshare.org")a.authority=BookshareUtils.environment==
"QA"?"public.qa."+BookshareUtils.domain:BookshareUtils.environment=="STAGING"?"public.staging."+BookshareUtils.domain:BookshareUtils.environment=="DEV"?"public.dev."+BookshareUtils.domain+":8080":"www."+BookshareUtils.domain;return a.toString()},raiseSystemAlert:function(a,b){var d=Handlebars.templates[a];$("#system-message-content").html(d(b!=null?b:{}));$("#system-message").modal({backdrop:"static",keyboard:!1})},dismissSystemAlert:function(){$("#system-message").modal("hide");$("#system-message-content").html("")},
beelineNotification:function(a){a.get("show_beeline_alert")&&((new BeeLineReader($("#beeline-notification-modal .modal-body p").get(0),{theme:"bright",skipBackgroundColor:!1,colorImmediately:!0,handleResize:!0})).color(),$("#beeline-notification-button-yes").click(function(){a.set("show_beeline_alert",!1);a.applyOptions();$("#beeline-notification-modal").modal("hide");$("#viewer-settings-modal").modal("show").attr("aria-hidden","true");$("#theme-radio-group span").each(function(){$(this).attr({"aria-selected":"false",
"aria-checked":"false"}).removeClass("selected")});$("#beeline-theme-option").trigger("click");$("#beeline-beta-menu #bright-button").trigger("click")}),$("#beeline-notification-button-no").click(function(){a.set("show_beeline_alert",!1);a.applyOptions();$("#beeline-notification-modal").modal("hide").attr("aria-hidden","true")}),$("#beeline-notification-modal").modal("show").attr("aria-hidden","false"))},findTopElement:function(a){for(var b=a.getFrame(),a=a.model.epub.get("page_prog_dir")=="rtl"?
2*parseInt(b.width.replace("px",""),10)/3:parseInt(b.width.replace("px",""),10)/3,d=null,e=parseInt(b.height.replace("px",""),10),b=b.contentDocument,c=0,d=b.elementFromPoint(a,c);c<e&&d!=null&&this.POSITION_TRACKING_EXCLUSIONS.indexOf(d.tagName.toLowerCase())>-1;)c+=10,d=b.elementFromPoint(a,c);return d},getSelectorForNearestElementWithId:function(a){var b=null;a.getAttribute("id")!=null?b=a.tagName+"#"+a.getAttribute("id"):a.previousElementSibling!=null?b=this.getSelectorForNearestElementWithId(a.previousElementSibling):
a.parentElement!=null&&this.POSITION_TRACKING_EXCLUSIONS.indexOf(a.parentElement.tagName.toLowerCase())==-1&&(b=this.getSelectorForNearestElementWithId(a.parentElement));return b},getSplitUrl:function(a){return a.match(/([^#]*)(?:#(.*))?/)},isIE9:function(){if(this.ie9Flag==null){for(var a=3,b=document.createElement("div"),d=b.getElementsByTagName("i");b.innerHTML="<\!--[if gt IE "+ ++a+"]><i></i><![endif]--\>",d[0];);this.ie9Flag=a===9?!0:!1}return this.ie9Flag},setFocus:function(a){var b=$(window._epubController.paginator.v.getFrame());
b.focus();var d=b.contents().find("#"+a);$(d).length>0&&setTimeout(function(){d.attr("tabindex","-1").focus()},500)},getRelativePath:function(a){var b=window._epubController.get("publication_root");if(a.indexOf(b)!==-1)return a.replace(b,"")}};
Readium.Models.PackageDocument.prototype.sync=BookshareUtils.makeSyncFunction(function(a){var b=a.get("book"),a=BookshareUtils.http+"www.bookshare.org/getManifest?titleInstanceId="+b.get("key"),b=b.get("tagId");a+=b?"&tag="+b:"";return BookshareUtils.resolveEnvironment(a)},"xml",BookshareUtils.isIE9());Readium.Models.Toc.prototype.sync=BookshareUtils.makeSyncFunction(function(a){return a.file_path},"xml");
Readium.Models.SpineItem.prototype.sync=window.BookshareUtils.makeSyncFunction(function(a){return a.get("href")},"xml");
Readium.Models.SpineItem.prototype.parse=function(a){var b=this,a=$(a);a.find("head [href]").each(function(){this.setAttribute("href",BookshareUtils.resolveUrl(this.getAttribute("href")))});a.find("[src]").each(function(){this.setAttribute("src",BookshareUtils.resolveUrl(this.getAttribute("src")))});a.find("aside[epub\\:type=annotation]").each(function(a,b){b.style.display="none"});a.find("a[href]").each(function(a,e){e.getAttribute("href").indexOf("#")=="0"&&this.setAttribute("href",BookshareUtils.getRelativePath(b.get("href"))+
e.getAttribute("href"))});a.find("[epub\\:type=pagebreak]").each(function(a,b){$(b).addClass("bksPageNumber");b.textContent==""&&b.getAttribute("title")!=""?b.textContent=b.getAttribute("title"):b.textContent!=""&&b.getAttribute("title")==""&&b.setAttribute("title",b.textContent)});this.content=a[0].documentElement};Readium.Models.PackageDocument.prototype.resolvePath=function(a){return a};
Readium.Models.PackageDocument.prototype.initialize=function(){this.uri_obj=new URI(this.get("book").get("publication_root"));this.on("change:spine_position",this.onSpinePosChanged)};
Readium.Models.PackageDocument.prototype.spineIndexFromHref=function(a){for(var b=this.get("res_spine"),a=new URI(this.resolveUri(a)),d=a.path.substring(a.path.lastIndexOf("/")+1),e=0;e<b.length;e++){var c=b.at(e).get("href"),c=new URI(this.resolveUri(c)),f=c.path.lastIndexOf("%2F")===-1?"/":"%2F",f=c.path.substring(c.path.lastIndexOf(f)+f.length);if(a.scheme===c.scheme&&a.authority===c.authority&&f==d)return e}return-1};
window.XDomainRequest&&BookshareUtils.isIE9()&&jQuery.ajaxTransport(function(a){if(a.crossDomain&&a.async){if(a.timeout)a.xdrTimeout=a.timeout,delete a.timeout;var b;return{send:function(d,e){function c(a,c,d,g){b.onload=b.onerror=b.ontimeout=jQuery.noop;b=void 0;e(a,c,d,g)}b=new XDomainRequest;b.onload=function(){c(200,"OK",{text:b.responseText},"Content-Type: "+b.contentType)};b.onerror=function(){c(404,"Not Found")};b.onprogress=function(){console.log("Fetch in progress")};b.ontimeout=function(){c(0,
"timeout")};b.timeout=1E4;b.open(a.type,a.url);b.send(a.hasContent&&a.data||null)},abort:function(){if(b)b.onerror=jQuery.noop,b.abort()}}}});if(window.BeneSpeak!=null)BeneSpeak._isBlockElement=function(a){a=window.frames[0].getComputedStyle(a);return a.display.indexOf("inline")==-1&&a.display.indexOf("ruby")==-1};
