Readium.Views.OptionsView=Backbone.View.extend({el:"#viewer-settings-modal",DEFAULT_VOICES:["Alex","native"],initialize:function(){console.log("Initializing options menu.");this.model.on("change:current_margin",this.renderMarginRadio,this);this.model.on("change:current_theme",this.renderTheme,this);var a=this;this.model.get("controller").get("columns_supported")||($("#setting-header-display-legend").toggle(!1),$("#pagination_mode").toggle(!1));this.model.get("controller").get("isIosDevice")&&$("#scrolling-option").toggle(!1);
$(".ttsOnly").toggle(BookshareUtils.hasSpeechAPI()||!!window.chrome&&!!window.chrome.tts);Acc.rg={theme:new Acc.RadioGroup("theme-radio-group"," ."+this.model.get("current_theme"),function(b){b=b.id;b==="default-theme-option"&&a.model.set("current_theme","default-theme");b==="night-theme-option"&&a.model.set("current_theme","night-theme");b==="parchment-theme-option"&&a.model.set("current_theme","parchment-theme");b==="beeline-theme-option"&&a.model.set("current_theme","beeline-theme")}),margin:new Acc.RadioGroup("margin-radio-wrapper",
" #margin-option-"+this.model.get("current_margin"),function(b){b=b.id;b=b[b.length-1];b==="1"&&a.model.set("current_margin",1);b==="2"&&a.model.set("current_margin",2);b==="3"&&a.model.set("current_margin",3);b==="4"&&a.model.set("current_margin",4);b==="5"&&a.model.set("current_margin",5)})};$("#options-btn").attr("aria-pressed","false");$("#viewer-settings-modal").on("show",function(){a.render()});$("#viewer-settings-modal").on("shown",function(){a.model.get("controller").set("options-view-shown",
!0);$("#options-heading").focus();setTimeout(function(){$("#options-btn").attr("aria-pressed","true")},1)}).on("hidden",function(){a.model.get("controller").set("options-view-shown",!1);setTimeout(function(){$("#options-btn").attr("aria-pressed","false").focus()},1)})},renderBeelineOption:function(){var a=this.model.get("beeline_theme");$("ul#beeline-beta-menu li").removeClass("active");$("li#"+a+"-button").addClass("active")},render:function(){this.renderPagination();this.renderTheme();this.renderBeelineOption();
this.renderMarginRadio();this.renderFontSize();this.renderFontFace();this.renderDisplayPageNumbers();if(BookshareUtils.hasSpeechAPI()&&(this.renderSpeechRate(),this.renderVoiceOptions(),window.chrome))speechSynthesis.onvoiceschanged=_.bind(this.renderVoiceOptions,this);return this},renderTheme:function(){var a=this.model.get("current_theme");this.$("#default-theme-option").toggleClass("selected",a=="default-theme");this.$("#night-theme-option").toggleClass("selected",a=="night-theme");this.$("#parchment-theme-option").toggleClass("selected",
a=="parchment-theme");this.$("#beeline-theme-option").toggleClass("selected",a=="beeline-theme");return this},renderMarginRadio:function(){var a="#margin-option-"+this.model.get("current_margin");this.$(".margin-radio").toggleClass("selected",!1);this.$(a).toggleClass("selected",!0);return this},renderFontSize:function(){var a=this.model.get("font_size");this.$("#font-size-input").val(a)},renderFontFace:function(){var a=this.model.get("font_face");this.$("#font-face-input").val(a)},renderPagination:function(){var a=
this.model.get("pagination_mode");this.$("#pagination-mode-input").val(a)},filterVoiceOptions:function(a){return a.localService&&(a.name=="US English Female TTS (by Google)"||!/google/i.test(a.voiceURI))},renderVoiceOptions:function(){var a,b=$("#voice-input");b.children().remove();var c=speechSynthesis.getVoices().filter(this.filterVoiceOptions);for(i=0;i<c.length;i++){var d=c[i],e=$("<option>").text(d.name).val(d.voiceURI);b.append(e);if(i==0||this.DEFAULT_VOICES.indexOf(d.name)>=0)a=d.voiceURI}c=
b.find("option[value='"+a+"']");c.text(c.text()+" (default)");c=this.model.get("voice_uri");b.val(c?c:a);a=this.model.get("controller");a.set("voice_uri",b.val());a.trigger("change:voice_uri")},renderSpeechRate:function(){var a=this.model.get("speech_rate");this.$("#speech-rate-input").val(a)},renderDisplayPageNumbers:function(){this.$("#display-page-numbers").prop("checked",this.model.get("display_page_numbers"))},events:{"click .theme-option":"selectTheme","click .margin-radio":"selectMargin","click #cancel-settings-but":"cancelSettings",
"click #save-settings-but":"applySettings","click #bright-button":function(){this.selectBeelineTheme("bright")},"click #dark-button":function(){this.selectBeelineTheme("dark")},"click #blues-button":function(){this.selectBeelineTheme("blues")},"click #gray-button":function(){this.selectBeelineTheme("gray")},"click #night_gray-button":function(){this.selectBeelineTheme("night_gray")}},selectBeelineTheme:function(a){a=="gray"&&console.log("Selecting gray theme.");this.model.set("current_theme","beeline-theme");
this.model.set("beeline_theme",a);this.renderTheme();this.renderBeelineOption()},unselectAllBeelineThemes:function(){$("#beeline-beta-menu li").each(function(){$(this).removeClass("active")})},selectTheme:function(a){var b=a.srcElement?a.srcElement.id:"";b&&a.srcElement&&Acc.rg&&Acc.rg.theme&&a.srcElement!=Acc.rg.theme.selected&&Acc.rg.theme.set(b);b==="default-theme-option"&&(this.model.set("current_theme","default-theme"),this.unselectAllBeelineThemes(),this.model.set("beeline_theme",""));b==="night-theme-option"&&
(this.model.set("current_theme","night-theme"),this.unselectAllBeelineThemes(),this.model.set("beeline_theme",""));b==="parchment-theme-option"&&(this.model.set("current_theme","parchment-theme"),this.unselectAllBeelineThemes(),this.model.set("beeline_theme",""));b==="beeline-theme-option"&&(this.model.set("current_theme","beeline-theme"),this.selectBeelineTheme("bright"));a.stopPropagation()},selectMargin:function(a){var b=a.srcElement.id;a.srcElement&&Acc.rg&&Acc.rg.margin&&a.srcElement!=Acc.rg.margin.selected&&
Acc.rg.margin.set(b);b=b[b.length-1];b==="1"&&this.model.set("current_margin",1);b==="2"&&this.model.set("current_margin",2);b==="3"&&this.model.set("current_margin",3);b==="4"&&this.model.set("current_margin",4);b==="5"&&this.model.set("current_margin",5);a.stopPropagation()},cancelSettings:function(){this.$el.modal("hide");this.model.resetOptions();$("#options-btn").focus()},applySettings:function(){this.model.set("display_page_numbers",this.$("#display-page-numbers").prop("checked"));this.model.set("pagination_mode",
$("#pagination-mode-input").val());this.model.set("font_size",parseInt($("#font-size-input").val(),10));this.model.set("font_face",$("#font-face-input").val());this.model.set("speech_rate",parseFloat($("#speech-rate-input").val()));this.model.set("voice_uri",$("#voice-input").val());this.model.applyOptions();this.$el.modal("hide");$("#options-btn").focus()}});
