Readium.Models.EPUBController=Backbone.Model.extend({initialize:function(){var a=this;this.epub=this.get("epub");this.options=Readium.Models.ReadiumOptions.getInstance();this.set("columns_supported",Modernizr.testProp(Modernizr.prefixed("columnWidth")));this.get("columns_supported")||this.options.set("pagination_mode","scrolling");var c=window.navigator.userAgent;c.indexOf("Safari")>=0&&c.indexOf("Mobile")>=0&&(this.set("isIosDevice",!0),this.options.set("pagination_mode","single"));this.options.set("controller",
this);this.options.applyOptions();this.paginator=new Readium.Models.PaginationStrategySelector({book:this});this.packageDocument=this.epub.getPackageDocument();this.packageDocument.fetch({success:function(){var b=a.restorePosition();a.set("spine_position",b);a.set("reading_position",a.loadReadingPosition());b=a.paginator.renderSpineItems(!1);a.set("rendered_spine_items",b);a.set("has_toc",!!a.packageDocument.getTocItem())}});this.on("change:spine_position",this.savePosition,this);this.on("change:spine_position",
this.clearReadingPosition,this);this.on("change:spine_position",this.setMetaSize,this);this.on("change:reading_position",this.saveReadingPosition,this);if(BookshareUtils.hasSpeechAPI())this.ttsPlayer=new Readium.Models.TTSPlayer({controller:this}),this.on("change:voice_uri",this.setTTSVoice,this);this.on("change:font_face",this.reportFontChange,this);this.on("change:current_theme",this.reportThemeChange,this);this.on("change:beeline_theme",this.reportThemeChange,this)},defaults:{font_size:10,font_face:"default",
display_page_numbers:!0,should_scroll:!1,two_up:!1,full_screen:!1,toolbar_visible:!0,toc_visible:!1,rendered_spine_items:[],current_theme:"default-theme",current_margin:3,track_position:!0,reading_position:null,beeline_theme:"bright"},toggleFullScreen:function(){this.set({full_screen:!this.get("full_screen")})},increaseFont:function(){this.set({font_size:this.get("font_size")+1})},decreaseFont:function(){this.set({font_size:this.get("font_size")-1})},toggleToc:function(){this.set("toc_visible",!this.get("toc_visible"))},
goToHref:function(a){a=BookshareUtils.getSplitUrl(a);this.trigger("goToHref");a[1]&&this.setSpinePos(this.packageDocument.spineIndexFromHref(a[1]),!1,a[2])},getToc:function(){var a=this.packageDocument.getTocItem();return a?Readium.Models.Toc.getToc(a,{file_path:this.resolvePath(a.get("href")),book:this}):null},getCurrentSection:function(a){a||(a=0);return this.packageDocument.getSpineItem(this.get("spine_position")+a)},isFixedLayout:function(){return this.epub.isFixedLayout()},restorePosition:function(){var a=
Readium.Utils.getCookie(this.epub.get("key"));return parseInt(a,10)||this.packageDocument.getNextLinearSpinePostition()},savePosition:function(){Readium.Utils.setCookie(this.epub.get("key"),this.get("spine_position"),365)},loadReadingPosition:function(){return Readium.Utils.getCookie(this.epub.get("key")+"_rp")},saveReadingPosition:function(){this.get("reading_position")!=null&&Readium.Utils.setCookie(this.epub.get("key")+"_rp",this.get("reading_position"),365)},clearReadingPosition:function(){this.set("reading_position",
null)},resolvePath:function(a){return this.packageDocument.resolvePath(a)},hasNextSection:function(){return this.packageDocument.getPrevLinearSpinePostition(this.get("spine_position"))>-1},hasPrevSection:function(){return this.packageDocument.getNextLinearSpinePostition(this.get("spine_position"))>-1},goToNextSection:function(){var a=this.packageDocument.getNextLinearSpinePostition(this.get("spine_position"));a>-1?this.setSpinePos(a,!1):alert("You have reached the end of this book.")},goToPrevSection:function(){var a=
this.packageDocument.getPrevLinearSpinePostition(this.get("spine_position"));a>-1?this.setSpinePos(a,!0):alert("You are at the beginning of this book.")},setSpinePos:function(a,c,b){if(!(a<0||a>=this.packageDocument.spineLength())){var d=this.get("rendered_spine_items").indexOf(a)>=0?!0:!1;this.set("spine_position",a);this.trigger("FXL_goToPage");d?!this.isFixedLayout()&&b&&this.paginator.v.goToHashFragment(b):this.set("rendered_spine_items",this.paginator.renderSpineItems(c,b))}},setMetaSize:function(){this.meta_section&&
this.meta_section.off("change:meta_height",this.setMetaSize);this.meta_section=this.getCurrentSection();this.meta_section.get("meta_height")&&this.set("meta_size",{width:this.meta_section.get("meta_width"),height:this.meta_section.get("meta_height")});this.meta_section.on("change:meta_height",this.setMetaSize,this)},setTTSVoice:function(){var a=this.get("voice_uri"),c=speechSynthesis.getVoices();for(i=0;i<c.length;i++){var b=c[i];if(b.voiceURI==a){this.ttsPlayer.set("voice",b);break}}},reportFontChange:function(){var a=
this.get("font_face");ga("send","event","Set Preference","Font Face",a?a:"default")},reportThemeChange:function(){var a=this.get("current_theme"),c=this.get("beeline_theme");ga("send","event","Set Preference","Theme",a+(a=="beeline-theme"?"-"+c:""))}});setInterval(function(){window._epub.packageDocument.fetch({success:function(){}})},18E5);
