Readium.Models.PackageDocumentParser=function(a){this.uri_obj=a};
Readium.Models.PackageDocumentParser.JathTemplate={metadata:{id:"//def:metadata/dc:identifier",epub_version:"//def:package/@version",title:"//def:metadata/dc:title",author:"//def:metadata/dc:creator",publisher:"//def:metadata/dc:publisher",description:"//def:metadata/dc:description",rights:"//def:metadata/dc:rights",language:"//def:metadata/dc:language",pubdate:"//def:metadata/dc:date",modified_date:"//def:metadata/def:meta[@property='dcterms:modified']",layout:"//def:metadata/def:meta[@property='rendition:layout']",
spread:"//def:metadata/def:meta[@property='rendition:spread']",orientation:"//def:metadata/def:meta[@property='rendition:orientation']",ncx:"//def:spine/@toc",page_prog_dir:"//def:spine/@page-progression-direction",active_class:"//def:metadata/def:meta[@property='media:active-class']"},manifest:["//def:item",{id:"@id",href:"@href",media_type:"@media-type",properties:"@properties",media_overlay:"@media-overlay"}],spine:["//def:itemref",{idref:"@idref",properties:"@properties",linear:"@linear"}],bindings:["//def:bindings/def:mediaType",
{handler:"@handler",media_type:"@media-type"}]};
Readium.Models.PackageDocumentParser.prototype.parse=function(a){var c;c=typeof a==="string"?(new window.DOMParser).parseFromString(a,"text/xml"):a;a={};a.metadata=this.getJsonMetadata(c);a.bindings=this.getJsonBindings(c);a.spine=this.getJsonSpine(c);a.manifest=this.getJsonManifest(c);a.paginate_backwards=this.paginateBackwards(c);if(c=this.getCoverHref(c))a.metadata.cover_href=this.resolveUri(c);if(a.metadata.layout==="pre-paginated")a.metadata.fixed_layout=!0;a.manifest=new Readium.Collections.ManifestItems(a.manifest,
{packageDocument:this});a.spine=this.parseSpineProperties(a.spine);return a};Readium.Models.PackageDocumentParser.prototype.getJsonSpine=function(a){var c=[],a=$("spine",a).children();$.each(a,function(a,e){var d=$(e),d={idref:d.attr("idref")?d.attr("idref"):"",linear:d.attr("linear")?d.attr("linear"):"",properties:d.attr("properties")?d.attr("properties"):""};c.push(d)});return c};
Readium.Models.PackageDocumentParser.prototype.getJsonMetadata=function(a){var c=$("metadata",a),b={};b.active_class=$("meta[property='media:active-class']",c).text();b.author=$("creator",c).text();b.description=$("description",c).text();b.epub_version=$("package",a).attr("version")?$("package",a).attr("version"):"";b.id=$("identifier",c).text();b.language=$("language",c).text();b.layout=$("meta[property='rendition:layout']",c).text();b.modified_date=$("meta[property='dcterms:modified']",c).text();
b.ncx=$("spine",a).attr("toc")?$("spine",a).attr("toc"):"";b.orientation=$("meta[property='rendition:orientation']",c).text();b.page_prog_dir=$("spine",a).attr("page-progression-direction")?$("spine",a).attr("page-progression-direction"):"";b.pubdate=$("date",c).text();b.publisher=$("publisher",c).text();b.rights=$("rights").text();b.spread=$("meta[property='rendition:spread']",c).text();b.title=$("title",c).text();return b};
Readium.Models.PackageDocumentParser.prototype.getJsonManifest=function(a){var a=$("manifest",a).children(),c=[];$.each(a,function(a,e){var d=$(e),d={href:d.attr("href")?d.attr("href"):"",id:d.attr("id")?d.attr("id"):"",media_overlay:d.attr("media-overlay")?d.attr("media-overlay"):"",media_type:d.attr("media-type")?d.attr("media-type"):"",properties:d.attr("properties")?d.attr("properties"):""};c.push(d)});return c};
Readium.Models.PackageDocumentParser.prototype.getJsonBindings=function(a){var a=$("bindings",a).children(),c=[];$.each(a,function(a,e){var d=$(e),d={handler:d.attr("handler")?d.attr("handler"):"",media_type:d.attr("media-type")?d.attr("media-type"):""};c.push(d)});return c};
Readium.Models.PackageDocumentParser.prototype.getCoverHref=function(a){var c,b;c=a.getElementsByTagName("manifest")[0];b=$('item[properties~="cover-image"]',c);if(b.length===1&&b.attr("href"))return b.attr("href");a=$('meta[name="cover"]',a);b=a.attr("content");if(a.length===1&&b&&(b=$('item[id="'+b+'"]',c),b.length===1&&b.attr("href")))return b.attr("href");b=$("#cover",c);return b.length===1&&b.attr("href")?b.attr("href"):null};
Readium.Models.PackageDocumentParser.prototype.parseSpineProperties=function(a){for(var c=function(a){for(var c={},a=a.split(" "),b=0;b<a.length;b++){if(a[b]==="rendition:page-spread-center")c.page_spread="center";if(a[b]==="page-spread-left")c.page_spread="left";if(a[b]==="page-spread-right")c.page_spread="right";if(a[b]==="page-spread-right")c.page_spread="right";if(a[b]==="rendition:layout-reflowable")c.fixed_flow=!1;if(a[b]==="rendition:layout-pre-paginated")c.fixed_flow=!0}return c},b=0;b<a.length;b++){var e=
c(a[b].properties);_.extend(a[b],e)}return a};Readium.Models.PackageDocumentParser.prototype.paginateBackwards=function(a){return $("spine",a).attr("page-progression-direction")==="ltr"};
Readium.Models.PackageDocumentParser.prototype.crunchSpine=function(a,c){var b=this,e=-1,d=_.map(a,function(a){e+=1;var d=c.find(function(b){if(b.get("id")===a.idref)return b}),f=b.get("book");return _.extend({},a,d.attributes,{spine_index:e},{page_prog_dir:f.get("page_prog_dir")})});return new Readium.Collections.Spine(d,{packageDocument:this})};Readium.Models.PackageDocumentParser.prototype.resolveUri=function(a){uri=new URI(a);return uri.resolve(this.uri_obj).toString()};
