Readium.Models.TTSPlayer=Backbone.Model.extend({defaults:{tts_playing:!1,currentNode:null,bufferSize:5E3,currentSpeech:null,voice:null},ALWAYS_SPEAK:["ol","ul","dl","table"],initialize:function(){this.controller=this.get("controller");this.bufferSize=this.get("bufferSize");this.controller.on("change:spine_position",this.stop,this);this.controller.on("goToHref",this.stop,this);this.controller.on("change:options-view-shown",this.stop,this);this.controller.on("change:toc_visible",this.stop,this);this.controller.on("pagesNextPage",
this.stop,this);this.controller.on("pagesPrevPage",this.stop,this);this.controller.on("repagination_event",this._windowSizeChangeHandler,this);$(window).unload(function(){speechSynthesis.cancel()})},play:function(){this.set("tts_playing",!0);this.controller.set("track_position",!1);this._setCurrentNode(this._getStartNode());this.speak()},stop:function(){speechSynthesis.pause();this.set("tts_playing",!1);this.set("currentNode",null);this.controller.set("track_position",!0);this.data=null;speechSynthesis.cancel()},
speak:function(){var a=this._getCurrentNode();if(a!=null){console.debug("SPEAKING: "+this._getCurrentNode().id);this.data=BeneSpeak.generateSpeechData(a);a=new SpeechSynthesisUtterance(this.data.utterance);console.debug("TTS TEXT: "+a.text.substr(0,40));a.voice=this.get("voice");a.rate=this.controller.options.get("speech_rate");var b=this._createCallbackHandler(this);a.onboundary=b;a.onend=b;a.onerror=b;speechSynthesis.speak(a);this.set("currentSpeech",a)}else this.stop()},advanceReadingPosition:function(){var a=
this._getCurrentNode(),a=this._getNextReadableNode(a);a!=null&&this._setCurrentNode(a);return a},_getNextReadableNode:function(a,b){var c=b?a:this._getNextNode(a);return c!=null?this._shouldRead(c)?this._shouldDescend(c)?this._getNextReadableNode(c.childNodes[0],!0):c:this._getNextReadableNode(c):null},_shouldDescend:function(a){if(a.nodeType==Node.ELEMENT_NODE){for(var b=!1,a=a.childNodes,c=0;c<a.length;c++){var d=a[c];if(d.nodeType==Node.ELEMENT_NODE&&(b=!0,!BeneSpeak._isBlockElement(d)))return!1}return b}else return!1},
_shouldRead:function(a){return a!=null&&a.textContent.trim().length>0&&(a.nodeType!=Node.ELEMENT_NODE||window.frames[0].getComputedStyle(a).display!="none"||a.getAttribute("epub:type")=="annotation")},_getStartNode:function(){var a=this.controller.paginator.v.getBody().ownerDocument.body;return $(a).find(this.controller.get("reading_position"))[0]||a.children[0]},_setCurrentNode:function(a){this.set("currentNode",a);a.nodeType==Node.ELEMENT_NODE&&a.getAttribute("id")!=null&&this.controller.set("reading_position",
a.tagName.toLowerCase()+"#"+a.getAttribute("id"))},_getCurrentNode:function(){return this.get("currentNode")},_getNextNode:function(a){return a.nextSibling!=null?a.nextSibling:a.parentNode!=null?this._getNextNode(a.parentNode):null},_hasBlockLevelChildrenOnly:function(a){if(a.hasChildNodes()==!0){for(var b=a.childNodes.length,c=0;c<b;c++){var d=a.childNodes[c];if(d.nodeType==Node.TEXT_NODE&&d.textContent.trim().length>0)return!1;else if(d.nodeType!=Node.TEXT_NODE&&!BeneSpeak._isBlockElement(d))return!1}return!0}else return!1},
_createCallbackHandler:function(a){var b=a.data;return function(c){console.debug("EVENT: "+c.type+" "+c.name+" "+c.charIndex);if(c.type=="boundary"&&c.name=="word"){a.controller.options.get("pagination_mode")=="scrolling"?(b.xOffset=a.controller.paginator.v.getFrame().contentWindow.scrollX,b.yOffset=a.controller.paginator.v.getFrame().contentWindow.scrollY):(b.xOffset=b._getOffset(b.document.documentElement.style.left),b.yOffset=b._getOffset(b.document.documentElement.style.top));var d=b.sentenceAt(c.charIndex);
d>=0&&b.highlightSentence(d);c=b.wordAt(c.charIndex);c>=0&&(d=a._getEnclosingAside(b.words[c].range.startContainer.parentElement),d!=null&&d.getAttribute("epub:type")=="annotation"?a._highlightImageGroup(d):b.highlightWord(c),a._updatePagePosition(b))}else if(c.type=="end")console.debug("END OF: "+a._getCurrentNode()),b.clearWordHighlight(),b.clearSentenceHighlight(),console.debug("TTS PLAYING? "+a.get("tts_playing")),a.get("tts_playing")&&a.advanceReadingPosition()!=null?(this.onend=null,console.debug("NEXT: "+
a._getCurrentNode().id),setTimeout(_.bind(a.speak,a),100)):setTimeout(_.bind(a.stop,a),100);else if(c.type=="error")console.debug("A TTS Error was encountered."),this.onerror=null,b.clearWordHighlight(),b.clearSentenceHighlight(),a.get("tts_playing")&&setTimeout(_.bind(a.stop,a),100)}},_updatePagePosition:function(a){var b=this.controller.paginator.v;b.getElemPageNumber!=null?a._wordRects.length>0&&(a=b.getElemPageNumber(a._wordRects[0]),b.pages.isPageVisible(a)||b.pages.goToPage(a)):a._wordRects.length>
0&&b.keepInCenter(a._wordRects[0])},_windowSizeChangeHandler:function(){if(this.get("tts_playing")){var a=this.data._highlightedSentence;this.data.clearSentenceHighlight();this.data.highlightSentence(a)}},_getEnclosingAside:function(a){for(;a!=null;)if(a.tagName.toLowerCase()=="aside")break;else a=a.parentElement;return a},_highlightImageGroup:function(a){this.data.clearWordHighlight();for(var a=a.parentElement.getClientRects(),b=0;b<a.length;b++){var c=this.data.document.createElement("div");this.data.document.body.appendChild(c);
c.className="ttsImgHL";c.style.position="absolute";c.style.top=a[b].top+window.scrollY+this.data.yOffset+"px";c.style.left=a[b].left+window.scrollX+this.data.xOffset+"px";c.style.width=a[b].width+"px";c.style.height=a[b].height+"px";this.data._wordRects.push(c)}},_logPath:function(a){var b="";if(a.nodeType==Node.TEXT_NODE)b="#text",a=a.parentElement;for(;a!=null;)var c=a.getAttribute("id"),b=a.tagName+(c!=null?"["+c+"]":"")+"/"+b,a=a.parentElement;return b}});
