Readium.Views.InjectedScrollingPaginationView=Readium.Views.PaginationViewBase.extend({initialize:function(a){Readium.Views.PaginationViewBase.prototype.initialize.call(this,a);this.page_template=Handlebars.templates.injected_scrolling_page_template;this.offset_dir=this.model.epub.get("page_prog_dir")==="rtl"?"right":"left";this.trackScrolling=!0;this.model.on("change:toc_visible",this.windowSizeChangeHandler,this);this.model.on("repagination_event",this.windowSizeChangeHandler,this);this.model.on("change:current_theme",
this.injectTheme,this);this.model.on("change:current_margin",this.marginCallback,this);this.model.on("change:beeline_theme",this.injectTheme,this);this.model.on("change:beeline_theme",this.beeLineCallback,this)},render:function(a,c){var b=this;this.model.getCurrentSection().content==null?(BookshareUtils.raiseSystemAlert("loading_content"),this.model.getCurrentSection().fetch({success:function(){BookshareUtils.dismissSystemAlert();b.renderInternal(a,c)}})):this.renderInternal(a,c);return[this.model.get("spine_position")]},
renderInternal:function(a,c){var b=this,e=this.model.getCurrentSection().toJSON(),f=this.model.getCurrentSection().content;this.$("#container").html(this.page_template(e));this.$("#readium-scrolling-content").on("load",function(d){if(!d.srcElement)d.srcElement=this;d.srcElement.contentDocument.documentElement.appendChild(f.children[0].cloneNode(!0));d.srcElement.contentDocument.documentElement.appendChild(f.children[1].cloneNode(!0));b.adjustIframe();b.iframeLoadCallback(d);b.setFontSize();b.setFontFace();
b.injectTheme();b.setBeeLine();b.getFrame().contentWindow.onscroll=b.makeScrollHandler();setTimeout(function(){c?b.goToHashFragment(c):(b.getFrame().focus(),a?b.getFrame().contentWindow.scrollBy(0,b.getBody().scrollHeight):b.model.get("reading_position")!=null?b.goToReadingPosition():(b.getFrame().contentWindow.scrollTo(0,0),b.getFrame().contentWindow.onscroll()))},250)})},getBody:function(){return this.$("#readium-scrolling-content").contents()[0].documentElement},getFrame:function(){return this.$("#readium-scrolling-content")[0]},
setFontSize:function(){var a=this.model.get("font_size")/10;$(this.getBody()).css("font-size",a+"em")},setFontFace:function(){var a=this.model.get("font_face");this.$("#readium-scrolling-content").contents().find("link#fontStyle").remove();a=="OpenDyslexic"&&this.$("#readium-scrolling-content").contents().find("head").append('<link id="fontStyle" rel="stylesheet" type="text/css" href="/fonts/OpenDyslexic/OpenDyslexic.css"/>');$(this.getBody()).css("font-family",a)},setBeeLine:function(){this.commonBeelineLogic(this.$("#readium-scrolling-content").contents())},
adjustIframe:function(){this.$("#readium-scrolling-content");this.setFrameSize()},setFrameSize:function(){var a=this.getFrameWidth().toString()+"px",c=this.getFrameHeight().toString()+"px";this.$("#readium-scrolling-content").attr("width",a);this.$("#readium-scrolling-content").attr("height",c);this.$("#readium-scrolling-content").css("width",a);this.$("#readium-scrolling-content").css("height",c);this.getBody().style.overflowX="hidden"},getFrameWidth:function(){var a;switch(this.model.get("current_margin")){case 1:a=
0.9;break;case 2:a=0.8;break;case 3:a=0.7;break;case 4:a=0.6;break;default:a=0.5}return Math.floor($("#scrolling-wrapper").width()*a)},getFrameHeight:function(){return $("#scrolling-wrapper").height()},windowSizeChangeHandler:function(){this.adjustIframe();this.goToReadingPosition()},marginCallback:function(){this.adjustIframe();this.goToReadingPosition()},pageNumberCallback:function(){this.togglePageNumbers();this.goToReadingPosition()},fontSizeCallback:function(){this.setFontSize();this.goToReadingPosition()},
fontFaceCallback:function(){this.setFontFace();this.goToReadingPosition()},beeLineCallback:function(){this.setBeeLine();this.goToReadingPosition()},goToHashFragment:function(a){var c=this.getFrame();c.focus();c.contentDocument.location.hash=a},keepInCenter:function(a){var c=this.getFrame(),b=this.getFrameHeight(),e=Number(a.style.top.replace("px",""));a.style.height.replace("px","");c.contentWindow.scrollTo(0,e-Math.round(0.25*b))},goToReadingPosition:function(){if(this.model.get("reading_position")!=
null){var a=$(this.getBody()).find(this.model.get("reading_position"));if(a.length>0)this.trackScrolling=!1,this.getFrame().contentWindow.scrollBy(0,a[0].getClientRects()[0].top),this.trackScrolling=!0}},makeScrollHandler:function(){var a=this;return function(){if(a.trackScrolling&&a.model.get("track_position")){var c=BookshareUtils.findTopElement(a,0.3);a.model.set("reading_position",BookshareUtils.getSelectorForNearestElementWithId(c))}}},destruct:function(){this.model.off("change:toc_visible",
this.windowSizeChangeHandler);this.model.off("repagination_event",this.windowSizeChangeHandler);this.model.off("change:current_theme",this.injectTheme);this.model.off("change:current_margin",this.marginCallback);this.model.off("change:beeline_theme",this.injectTheme);this.model.off("change:beeline_theme",this.beeLineCallback);this.getFrame().contentWindow.onscroll=null;Readium.Views.PaginationViewBase.prototype.destruct.call(this)}});
