Readium.Views.InjectedReflowablePaginationView=Readium.Views.PaginationViewBase.extend({initialize:function(a){Readium.Views.PaginationViewBase.prototype.initialize.call(this,a);this.page_template=Handlebars.templates.injected_reflowing_template;this.stashModernizrPrefixedProps();this.offset_dir=this.model.epub.get("page_prog_dir")==="rtl"?"right":"left";this.trackPosition=!0;this.pages.on("change:current_page",this.pageChangeHandler,this);this.model.on("change:toc_visible",this.windowSizeChangeHandler,
this);this.model.on("repagination_event",this.windowSizeChangeHandler,this);this.model.on("change:current_theme",this.injectTheme,this);this.model.on("change:two_up",this.setUpMode,this);this.model.on("change:two_up",this.windowSizeChangeHandler,this);this.model.on("change:current_margin",this.marginCallback,this);this.model.on("change:beeline_theme",this.injectTheme,this);this.model.on("change:beeline_theme",this.beeLineCallback,this)},render:function(a,b){var c=this;this.model.getCurrentSection().content==
null?(BookshareUtils.raiseSystemAlert("loading_content"),this.model.getCurrentSection().fetch({success:function(){BookshareUtils.dismissSystemAlert();c.renderInternal(a,b)}})):this.renderInternal(a,b);return[this.model.get("spine_position")]},renderInternal:function(a,b){var c=this,f=this.model.getCurrentSection().toJSON(),e=this.model.getCurrentSection().content;this.setUpMode();this.$("#container").html(this.page_template(f));this.$("#readium-flowing-content").on("load",function(d){if(!d.srcElement)d.srcElement=
this;d.srcElement.contentDocument.documentElement.appendChild(e.children[0].cloneNode(!0));d.srcElement.contentDocument.documentElement.appendChild(e.children[1].cloneNode(!0));c.adjustIframeColumns();c.iframeLoadCallback(d);c.setFontSize();c.setFontFace();c.injectTheme();c.setBeeLine();c.setNumPages();c.disableFocusAutoscroll();b?c.goToHashFragment(b):a?c.pages.goToLastPage():c.model.get("reading_position")!=null?c.goToReadingPosition():(c.pages.goToPage(1),c.goToPage(1))})},findVisiblePageElements:function(){var a=
$(this.getBody()).find("[id]"),b=$("#readium-flowing-content").contents()[0].documentElement,c=0+$(b).width(),b=0+$(b).height();return this.filterElementsByPosition(a,0,b,0,c)},filterElementsByPosition:function(a,b,c,f,e){return a.filter(function(){var a=$(this).offset().top,g=$(this).offset().left,h=g+$(this).width(),i=a+$(this).height(),a=a>=b&&i<=c;return g>=f&&h<=e&&a})},destruct:function(){this.hideContent();this.pages.off("change:current_page",this.pageChangeHandler);this.model.off("change:toc_visible",
this.windowSizeChangeHandler);this.model.off("repagination_event",this.windowSizeChangeHandler);this.model.off("change:current_theme",this.injectTheme);this.model.off("change:two_up",this.setUpMode);this.model.off("change:two_up",this.windowSizeChangeHandler);this.model.off("change:current_margin",this.marginCallback);this.model.off("change:beeline_theme",this.injectTheme);this.model.off("change:beeline_theme",this.beeLineCallback);Readium.Views.PaginationViewBase.prototype.destruct.call(this)},goToPage:function(a){a=
this.calcPageOffset(a).toString()+"px";$(this.getBody()).css(this.offset_dir,"-"+a);this.showContent();this.trackPosition&&this.model.get("track_position")&&BookshareUtils.findTopElement(this)&&this.model.set("reading_position",BookshareUtils.getSelectorForNearestElementWithId(BookshareUtils.findTopElement(this)))},goToHashFragment:function(a){if(a&&(a=$("#"+a,this.getBody())[0])){for(;a.children.length>0;)a=a.children[0];var b=this.getElemPageNumber(a);this.trackPosition&&this.model.get("track_position")&&
this.model.set("reading_position",BookshareUtils.getSelectorForNearestElementWithId(a));if(b>0)this.trackPosition=!1,this.pages.goToPage(b),this.goToPage(b),this.trackPosition=!0}},setFontSize:function(){var a=this.model.get("font_size")/10;$(this.getBody()).css("font-size",a+"em");this.setNumPages()},setFontFace:function(){var a=this.model.get("font_face");this.$("#readium-flowing-content").contents().find("link#fontStyle").remove();a=="OpenDyslexic"&&this.$("#readium-flowing-content").contents().find("head").append('<link id="fontStyle" rel="stylesheet" type="text/css" href="/fonts/OpenDyslexic/OpenDyslexic.css"/>');
$(this.getBody()).css("font-family",a);this.setNumPages()},setBeeLine:function(){this.commonBeelineLogic(this.$("#readium-flowing-content").contents())},stashModernizrPrefixedProps:function(){var a=function(a){return a.replace(/([A-Z])/g,function(a,b){return"-"+b.toLowerCase()}).replace(/^ms-/,"-ms-")};this.columAxis=Modernizr.prefixed("columnAxis")||"columnAxis";this.columGap=Modernizr.prefixed("columnGap")||"columnGap";this.columWidth=Modernizr.prefixed("columnWidth")||"columnWidth";this.cssColumAxis=
a(this.columAxis);this.cssColumGap=a(this.columGap);this.cssColumWidth=a(this.columWidth)},getBodyColumnCss:function(){var a={};a[this.cssColumAxis]="horizontal";a[this.cssColumGap]=this.gap_width.toString()+"px";a[this.cssColumWidth]=this.page_width.toString()+"px";a.padding="0px";a.margin="0px";a.position="absolute";a.width=this.page_width.toString()+"px";a.height=this.frame_height.toString()+"px";return a},adjustIframeColumns:function(){var a=this.$("#readium-flowing-content");this.setFrameSize();
this.frame_width=parseInt(a.width(),10);this.frame_height=parseInt(a.height(),10);this.gap_width=Math.floor(this.frame_width/7);this.page_width=this.model.get("two_up")?Math.floor((this.frame_width-this.gap_width)/2):this.frame_width;$(this.getBody()).css(this.getBodyColumnCss());this.setNumPages()},getBody:function(){return this.$("#readium-flowing-content").contents()[0].documentElement},getFrame:function(){return this.$("#readium-flowing-content")[0]},hideContent:function(){$("#flowing-wrapper").css("opacity",
"0")},showContent:function(){$("#flowing-wrapper").css("opacity","1")},calcPageOffset:function(a){return(a-1)*(this.page_width+this.gap_width)},setFrameSize:function(){var a=this.getFrameWidth().toString()+"px",b=this.getFrameHeight().toString()+"px";this.$("#readium-flowing-content").attr("width",a);this.$("#readium-flowing-content").attr("height",b);this.$("#readium-flowing-content").css("width",a);this.$("#readium-flowing-content").css("height",b)},getFrameWidth:function(){var a,b=this.model.get("current_margin");
b===1?this.model.get("two_up")?a=0.95:a=0.9:b===2?this.model.get("two_up")?a=0.89:a=0.8:b===3?this.model.get("two_up")?a=0.83:a=0.7:b===4?this.model.get("two_up")?a=0.77:a=0.6:this.model.get("two_up")?a=0.7:a=0.5;return Math.floor($("#flowing-wrapper").width()*a)},getFrameHeight:function(){return $("#flowing-wrapper").height()},calcNumPages:function(){var a,b,c;a=this.getBody();if(!a)return this.pages.get("num_pages");b=a.style[this.offset_dir];a.style[this.offset_dir]="0px";c=this.getBody().scrollWidth;
a.style[this.offset_dir]=b;a=Math.floor((c+this.gap_width)/(this.gap_width+this.page_width));a%2===0&&this.model.get("two_up");return a},getElemPageNumber:function(a){var b,a=a.getClientRects();if(!a||a.length<1)return-1;b=a[0][this.offset_dir];b+=Math.abs(a[0].left-a[0].right);this.offset_dir==="right"&&(b=this.page_width-b);b-=parseInt(this.getBody().style[this.offset_dir]||0,10);return Math.ceil(b/(this.page_width+this.gap_width))},getElemPageNumberById:function(a){var b=$("#readium-flowing-content").contents()[0].documentElement,
a=$(b).find("#"+a);return a.length==0?-1:this.getElemPageNumber(a[0])},pageChangeHandler:function(){var a=this;this.trackPosition&&(this.hideContent(),setTimeout(function(){a.goToPage(a.pages.get("current_page")[0])},150))},goToReadingPosition:function(){var a=this.pages.get("current_page")[0]||1,b=$(this.getBody()).find(this.model.get("reading_position"));b.length>0&&(b=this.getElemPageNumber(b[0]),!isNaN(b)&&b>0&&(a=b));this.trackPosition=!1;this.pages.goToPage(a);this.goToPage(a);this.trackPosition=
!0},windowSizeChangeHandler:function(){this.adjustIframeColumns();this.goToReadingPosition()},marginCallback:function(){this.adjustIframeColumns();this.goToReadingPosition()},pageNumberCallback:function(){this.togglePageNumbers();this.adjustIframeColumns();this.goToReadingPosition()},fontSizeCallback:function(){this.setFontSize();this.goToReadingPosition()},fontFaceCallback:function(){this.setFontFace();this.goToReadingPosition()},beeLineCallback:function(){this.setBeeLine();this.goToReadingPosition()},
setNumPages:function(){this.pages.set("num_pages",this.calcNumPages())},disableFocusAutoscroll:function(){var a=$(this.getBody()),b=a.find("body");b.find("a[href]").focus(function(){a.scrollLeft(0);setTimeout(function(){b.scrollLeft(0)},0)})}});
