Readium.Views.PaginationViewBase=Backbone.View.extend({el:"#readium-book-view-el",initialize:function(a){this.zoomer=a.zoomer;this.pages=new Readium.Models.ReadiumPagination({model:this.model});this.pages.on("change:current_page",this.showCurrentPages,this);this.model.on("change:display_page_numbers",this.pageNumberCallback,this);this.model.on("change:font_size",this.fontSizeCallback,this);this.model.on("change:font_face",this.fontFaceCallback,this);this.bindingTemplate=Handlebars.templates.binding_template;
this.shortcutTemplate=Handlebars.templates.iframe_keyboard_shortcuts},iframeLoadCallback:function(a){this.applyBindings($(a.srcElement).contents());this.applySwitches($(a.srcElement).contents());this.addSwipeHandlers($(a.srcElement).contents());this.injectHighlightStyles(a.srcElement);this.injectPageNumberStyles(a.srcElement);this.togglePageNumbers();this.injectLinkHandler(a.srcElement);this.injectKeyboardSupport(a.srcElement);var b=this.parseTriggers(a.srcElement.contentDocument);this.applyTriggers(a.srcElement.contentDocument,
b)},activateEPubStyle:function(a){var b;this.model.get("current_theme")==="night-theme"||this.model.get("current_theme")==="beeline-theme"&&this.model.get("beeline_theme")=="night_gray"?(b=new Readium.Models.AlternateStyleTagSelector,b.activateAlternateStyleSet(["night"],a)):(b=new Readium.Models.AlternateStyleTagSelector,b.activateAlternateStyleSet([""],a))},setUpMode:function(){var a=this.model.get("two_up");this.$el.toggleClass("two-up",a);this.$("#spine-divider").toggle(a)},showCurrentPages:function(){var a=
this,b=this.model.get("two_up");this.$(".page-wrap").each(function(c){b||(c+=1);$(this).toggleClass("hidden-page",!a.pages.isPageVisible(c))})},destruct:function(){this.pages.off("change:current_page",this.showCurrentPages);this.model.off("change:display_page_numbers",this.pageNumberCallback,this);this.model.off("change:font_face",this.fontFaceCallback);this.model.off("change:font_size",this.fontSizeCallback);this.resetEl()},linkClickHandler:function(a){a.preventDefault();a=$(a.currentTarget).attr("href");
a.match(/^http(s)?:/)?window.open(a):(this.model.goToHref(a),a=BookshareUtils.getSplitUrl(a),a[1]&&BookshareUtils.setFocus(a[2]))},getBindings:function(){var a=this.model.epub.getPackageDocument();return a.get("bindings").map(function(b){b.selector='object[type="'+b.media_type+'"]';b.url=a.getManifestItemById(b.handler).get("href");b.url=a.resolveUri(b.url);return b})},applyBindings:function(a){for(var b=this,c=this.getBindings(),d=0,d=0;d<c.length;d++)$(c[d].selector,a).each(function(){var a=[],
f=$(this),e=f.attr("data");a.push("src="+b.model.packageDocument.resolveUri(e));a.push("type="+c[d].media_type);a=c[d].url+"?"+a.join("&");e=$(b.bindingTemplate({}));e.attr("src",a);f.html(e)})},applyTriggers:function(a,b){for(var c=0;c<b.length;c++)b[c].subscribe(a)},parseTriggers:function(a){var b=[];$("trigger",a).each(function(){b.push(new Readium.Models.Trigger(this))});return b},applySwitches:function(a){$("switch",a).each(function(){var a=!1;$("case",this).each(function(){var c;if(c=!a)(c=
this.attributes["required-namespace"])?c=_.include(["http://www.w3.org/1998/Math/MathML"],c):(console.log("Encountered a case statement with no required-namespace"),c=!1);c?a=!0:$(this).remove()});a&&$("default",this).remove()})},addSwipeHandlers:function(a){var b=this;$(a).on("swipeleft",function(a){a.preventDefault();b.pages.goRight()});$(a).on("swiperight",function(a){a.preventDefault();b.pages.goLeft()})},togglePageNumbers:function(){var a=this;$(this.getBody()).find(".bksPageNumber").each(function(b,
c){if(a.model.get("display_page_numbers"))c.textContent=c.getAttribute("title"),$(c).addClass("bksPageNumberOn");else{for(;c.hasChildNodes();)c.removeChild(c.childNodes[0]);$(c).removeClass("bksPageNumberOn")}})},highlightThemes:{"default":".ttsImgHL { background-color: #3366AA; opacity: 0.5; z-index: 4242;}\n.ttsSentHL { background-color: #DDDDDD; z-index: -2; }\n.ttsWordHL { background-color: #99CCFF; z-index: -1;}",night:".ttsImgHL { background-color: #3366AA; opacity: 0.5; z-index: 4242;}\n.ttsSentHL { background-color: #B0C6F5; z-index: -2; }\n.ttsWordHL { background-color: #F37D01; z-index: -1;}"},
injectHighlightStyles:function(a){var b;b=a.contentDocument;if(a=b.getElementsByTagName("head")[0]){var c=$(a).find("#highlightStyle");c.length>0&&$(c.remove());b=b.createElement("style");$(b).attr("id","highlightStyle");b.type="text/css";var c=this.model.get("current_theme"),d=this.model.get("beeline_theme");b.innerHTML=c=="night-theme"||d=="night_gray"?this.highlightThemes.night:this.highlightThemes["default"];a.appendChild(b)}},injectPageNumberStyles:function(a){var b;b=a.contentDocument;if(a=
b.getElementsByTagName("head")[0])b=b.createElement("style"),b.type="text/css",b.innerHTML=".bksPageNumberOn { display:block; text-align: center; width: 25%; margin-left: auto; margin-right: auto; font-weight: bold; font-style: italic; border: 1px solid gray; }",a.appendChild(b)},injectLinkHandler:function(a){var b=this;$("a",a.contentDocument).click(function(a){b.linkClickHandler(a)})},injectKeyboardSupport:function(a){var b=this;$(a.contentDocument).keydown(function(a){a.which==39&&b.model.paginator.v.pages.goRight();
a.which==37&&b.model.paginator.v.pages.goLeft()});a=$(b.getBody()).find("body");a.append($(b.shortcutTemplate({ttsEnabled:window.chrome&&window.chrome.extension})));a.find("#hiddenAccessKeys a[accesskey]").bind("click",function(a){a.preventDefault();a=$(window.document.body).find("a[accesskey='"+a.currentTarget.getAttribute("accesskey")+"']");a.attr("href").search("#")==0?a.click():window.document.location=a.attr("href")})},injectTheme:function(){var a=this.model.get("current_theme"),b=this.model.get("beeline_theme"),
c=this.model.get("beeline_object");a==="default"&&(a="default-theme");a!="beeline-theme"?(this.$el.find("link#beeLineStyle").remove(),c&&c.uncolor()):c&&c.recolor();c=this.themes[a].color;a=="beeline-theme"&&b=="night_gray"&&(c="#FFFFFF");$(this.getBody()).css({color:c,"background-color":this.themes[a]["background-color"]});$("#flowing-wrapper").css("visibility","hidden");this.activateEPubStyle(this.getBody());this.injectHighlightStyles(this.getFrame());var d=this.model.options;setTimeout(function(){$("#flowing-wrapper").css("visibility",
"visible");BookshareUtils.beelineNotification(d)},100)},commonBeelineLogic:function(a){var b=this.model.get("current_theme");a.find("link#beeLineStyle").remove();this.$el.find('style[id^="beeline-custom-styles-"]').remove();console.log("commonBeelineLogic theme: "+b);b=="beeline-theme"&&(b=this.model.get("beeline_theme"),a.find("head").append('<link id="beeLineStyle" rel="stylesheet" type="text/css" href="/lib/beeline.min.css"/>'),(a=this.model.get("beeline_object"))&&a.cleanup(),console.log("New Beeline object with theme "+
b),a=new BeeLineReader($(this.getBody()).get(0),{theme:b,skipBackgroundColor:!1,colorImmediately:!0,handleResize:!0}),a.color(),this.model.set("beeline_object",a))},themes:{"default-theme":{"background-color":"white",color:"black","mo-color":"#777"},"parchment-theme":{"background-color":"#f7f1cf",color:"#774c27","mo-color":"#eebb22"},"night-theme":{"background-color":"#141414",color:"white","mo-color":"#666"},"beeline-theme":{"background-color":"white",color:"000000","mo-color":"#777"}},resetEl:function(){$("body").removeClass("apple-fixed-layout");
$("#readium-book-view-el").attr("style","");this.$el.toggleClass("two-up",!1);this.$("#spine-divider").toggle(!1);this.zoomer.reset();$("#page-wrap").css({position:"relative",right:"0px",top:"0px","-webkit-transform":"scale(1.0) translate(0px, 0px)"})}});
